url: https://cep5.github.io
#baseurl:

# Site settings
title: Ceptorico
email: ceptorico@gmail.com
description: "Website Development"
markdown: kramdown
permalink: /:categories/:title
fbcomments: yes
#media: http://localhost:4000
#media: https://cep5.updog.co